### ISSUE TITLE
Help: reading time not appearing

### ISSUE THREAD

**Issue by berot3** [darrenjennings/vuepress-plugin-reading-time#3]
I hope my quesiton is not too stupid, but I would like to sue this plugin on my vuepress.

I added it to my plugins in config.js but I can't see it displayed anywhere. Does this mean that the theme has to support it or that I have to implement it into the theme somehow?

Thanks for any help!

**Comment by darrenjennings** [comment]
Vuepress is fully extensible so this plugin doesn't add any UI, it only injects the `readingTime` object into the `$page` global object. For instance, I have a custom theme for my blog that injects the time at the top of the posts layout:

https://github.com/darrenjennings/guuu.io/blob/master/docs/.vuepress/theme/Layouts/Post.vue#L5
https://github.com/darrenjennings/guuu.io/blob/master/docs/.vuepress/components/ReadingTime.vue#L3

You could also just access inside markdown:

```md
---
permalink: /about
---

# About

This post is a {{ $page.readingTime.text }}
```
